import random
import threading
import os
import socket

from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSKernelSwitch, UserSwitch, OVSSwitch, Host
from mininet.cli import CLI
from mininet.log import setLogLevel
from mininet.link import TCLink, Link
from mininet.topo import Topo

class Network(Topo):

    def __init__(self):
        Topo.__init__(self)
        s0 = self.addSwitch('s0')
        s10 = self.addSwitch('s10')
        s8 = self.addSwitch('s8')
        s54 = self.addSwitch('s54')
        h1 = self.addHost('h1')
        s27 = self.addSwitch('s27')
        s2 = self.addSwitch('s2')
        s7 = self.addSwitch('s7')
        s69 = self.addSwitch('s69')
        s3 = self.addSwitch('s3')
        s98 = self.addSwitch('s98')
        s37 = self.addSwitch('s37')
        s79 = self.addSwitch('s79')
        s74 = self.addSwitch('s74')
        s93 = self.addSwitch('s93')
        h4 = self.addHost('h4')
        s49 = self.addSwitch('s49')
        s5 = self.addSwitch('s5')
        s6 = self.addSwitch('s6')
        s70 = self.addSwitch('s70')
        s75 = self.addSwitch('s75')
        s52 = self.addSwitch('s52')
        s44 = self.addSwitch('s44')
        s9 = self.addSwitch('s9')
        s87 = self.addSwitch('s87')
        s67 = self.addSwitch('s67')
        s57 = self.addSwitch('s57')
        h11 = self.addHost('h11')
        s65 = self.addSwitch('s65')
        s12 = self.addSwitch('s12')
        s42 = self.addSwitch('s42')
        s13 = self.addSwitch('s13')
        s30 = self.addSwitch('s30')
        s14 = self.addSwitch('s14')
        s64 = self.addSwitch('s64')
        s40 = self.addSwitch('s40')
        s15 = self.addSwitch('s15')
        s16 = self.addSwitch('s16')
        s96 = self.addSwitch('s96')
        s86 = self.addSwitch('s86')
        s76 = self.addSwitch('s76')
        s17 = self.addSwitch('s17')
        s26 = self.addSwitch('s26')
        s50 = self.addSwitch('s50')
        s18 = self.addSwitch('s18')
        s19 = self.addSwitch('s19')
        s53 = self.addSwitch('s53')
        s20 = self.addSwitch('s20')
        s21 = self.addSwitch('s21')
        s23 = self.addSwitch('s23')
        s24 = self.addSwitch('s24')
        h22 = self.addHost('h22')
        s39 = self.addSwitch('s39')
        s82 = self.addSwitch('s82')
        s77 = self.addSwitch('s77')
        s25 = self.addSwitch('s25')
        h47 = self.addHost('h47')
        s71 = self.addSwitch('s71')
        s83 = self.addSwitch('s83')
        s28 = self.addSwitch('s28')
        s90 = self.addSwitch('s90')
        s29 = self.addSwitch('s29')
        s88 = self.addSwitch('s88')
        s31 = self.addSwitch('s31')
        s43 = self.addSwitch('s43')
        s32 = self.addSwitch('s32')
        s81 = self.addSwitch('s81')
        s33 = self.addSwitch('s33')
        s34 = self.addSwitch('s34')
        s35 = self.addSwitch('s35')
        s60 = self.addSwitch('s60')
        s94 = self.addSwitch('s94')
        s36 = self.addSwitch('s36')
        h38 = self.addHost('h38')
        s56 = self.addSwitch('s56')
        s97 = self.addSwitch('s97')
        s41 = self.addSwitch('s41')
        s63 = self.addSwitch('s63')
        s45 = self.addSwitch('s45')
        s58 = self.addSwitch('s58')
        s46 = self.addSwitch('s46')
        s55 = self.addSwitch('s55')
        s48 = self.addSwitch('s48')
        h61 = self.addHost('h61')
        s51 = self.addSwitch('s51')
        s84 = self.addSwitch('s84')
        s80 = self.addSwitch('s80')
        s72 = self.addSwitch('s72')
        s73 = self.addSwitch('s73')
        s66 = self.addSwitch('s66')
        s92 = self.addSwitch('s92')
        s59 = self.addSwitch('s59')
        s62 = self.addSwitch('s62')
        s89 = self.addSwitch('s89')
        s68 = self.addSwitch('s68')
        s95 = self.addSwitch('s95')
        s78 = self.addSwitch('s78')
        h99 = self.addHost('h99')
        s85 = self.addSwitch('s85')
        s91 = self.addSwitch('s91')
        self.addLink(s0, s10, cls=TCLink, delay='14ms')
        self.addLink(s0, s8, cls=TCLink, delay='18ms')
        self.addLink(s0, s54, cls=TCLink, delay='13ms')
        self.addLink(h1, s27, cls=TCLink, delay='4ms')
        self.addLink(s2, s7, cls=TCLink, delay='1ms')
        self.addLink(s2, s69, cls=TCLink, delay='7ms')
        self.addLink(s3, s98, cls=TCLink, delay='20ms')
        self.addLink(s3, s37, cls=TCLink, delay='19ms')
        self.addLink(s3, s79, cls=TCLink, delay='16ms')
        self.addLink(s3, s74, cls=TCLink, delay='11ms')
        self.addLink(s3, s93, cls=TCLink, delay='4ms')
        self.addLink(h4, s49, cls=TCLink, delay='14ms')
        self.addLink(s5, s8, cls=TCLink, delay='20ms')
        self.addLink(s6, s70, cls=TCLink, delay='16ms')
        self.addLink(s6, s75, cls=TCLink, delay='7ms')
        self.addLink(s7, s52, cls=TCLink, delay='7ms')
        self.addLink(s7, s44, cls=TCLink, delay='5ms')
        self.addLink(s9, s87, cls=TCLink, delay='13ms')
        self.addLink(s9, s67, cls=TCLink, delay='16ms')
        self.addLink(s9, s57, cls=TCLink, delay='10ms')
        self.addLink(h11, s65, cls=TCLink, delay='19ms')
        self.addLink(s12, s42, cls=TCLink, delay='20ms')
        self.addLink(s13, s30, cls=TCLink, delay='10ms')
        self.addLink(s14, s64, cls=TCLink, delay='16ms')
        self.addLink(s14, s40, cls=TCLink, delay='13ms')
        self.addLink(s14, s69, cls=TCLink, delay='3ms')
        self.addLink(s14, s57, cls=TCLink, delay='1ms')
        self.addLink(s15, s93, cls=TCLink, delay='11ms')
        self.addLink(s16, s96, cls=TCLink, delay='16ms')
        self.addLink(s16, s86, cls=TCLink, delay='9ms')
        self.addLink(s16, s76, cls=TCLink, delay='8ms')
        self.addLink(s17, s26, cls=TCLink, delay='18ms')
        self.addLink(s17, s50, cls=TCLink, delay='17ms')
        self.addLink(s18, s42, cls=TCLink, delay='18ms')
        self.addLink(s19, s53, cls=TCLink, delay='5ms')
        self.addLink(s20, s57, cls=TCLink, delay='15ms')
        self.addLink(s21, s23, cls=TCLink, delay='19ms')
        self.addLink(s21, s24, cls=TCLink, delay='15ms')
        self.addLink(h22, s39, cls=TCLink, delay='3ms')
        self.addLink(s23, s82, cls=TCLink, delay='15ms')
        self.addLink(s23, s77, cls=TCLink, delay='1ms')
        self.addLink(s25, s53, cls=TCLink, delay='1ms')
        self.addLink(s25, s39, cls=TCLink, delay='4ms')
        self.addLink(s26, h47, cls=TCLink, delay='8ms')
        self.addLink(s27, s71, cls=TCLink, delay='17ms')
        self.addLink(s27, s83, cls=TCLink, delay='9ms')
        self.addLink(s28, s90, cls=TCLink, delay='18ms')
        self.addLink(s29, s93, cls=TCLink, delay='9ms')
        self.addLink(s30, s88, cls=TCLink, delay='8ms')
        self.addLink(s31, s43, cls=TCLink, delay='16ms')
        self.addLink(s31, s52, cls=TCLink, delay='1ms')
        self.addLink(s31, s49, cls=TCLink, delay='15ms')
        self.addLink(s32, s96, cls=TCLink, delay='5ms')
        self.addLink(s32, s81, cls=TCLink, delay='10ms')
        self.addLink(s33, s88, cls=TCLink, delay='3ms')
        self.addLink(s34, s52, cls=TCLink, delay='17ms')
        self.addLink(s35, s60, cls=TCLink, delay='18ms')
        self.addLink(s35, s94, cls=TCLink, delay='11ms')
        self.addLink(s36, s52, cls=TCLink, delay='10ms')
        self.addLink(h38, s56, cls=TCLink, delay='4ms')
        self.addLink(s40, s97, cls=TCLink, delay='6ms')
        self.addLink(s40, s90, cls=TCLink, delay='3ms')
        self.addLink(s41, s63, cls=TCLink, delay='1ms')
        self.addLink(s42, s71, cls=TCLink, delay='10ms')
        self.addLink(s44, s76, cls=TCLink, delay='15ms')
        self.addLink(s45, s96, cls=TCLink, delay='12ms')
        self.addLink(s45, s58, cls=TCLink, delay='1ms')
        self.addLink(s45, s88, cls=TCLink, delay='5ms')
        self.addLink(s46, s63, cls=TCLink, delay='15ms')
        self.addLink(s46, s55, cls=TCLink, delay='18ms')
        self.addLink(s48, s94, cls=TCLink, delay='9ms')
        self.addLink(s48, h61, cls=TCLink, delay='8ms')
        self.addLink(s50, s74, cls=TCLink, delay='3ms')
        self.addLink(s50, s75, cls=TCLink, delay='2ms')
        self.addLink(s51, s84, cls=TCLink, delay='13ms')
        self.addLink(s51, s80, cls=TCLink, delay='17ms')
        self.addLink(s51, s75, cls=TCLink, delay='4ms')
        self.addLink(s53, s72, cls=TCLink, delay='6ms')
        self.addLink(s53, s76, cls=TCLink, delay='4ms')
        self.addLink(s54, s73, cls=TCLink, delay='10ms')
        self.addLink(s54, s66, cls=TCLink, delay='5ms')
        self.addLink(s55, s92, cls=TCLink, delay='11ms')
        self.addLink(s56, s82, cls=TCLink, delay='11ms')
        self.addLink(s59, s62, cls=TCLink, delay='8ms')
        self.addLink(s59, s89, cls=TCLink, delay='5ms')
        self.addLink(s60, s68, cls=TCLink, delay='18ms')
        self.addLink(s63, s88, cls=TCLink, delay='15ms')
        self.addLink(s65, s84, cls=TCLink, delay='9ms')
        self.addLink(s67, s95, cls=TCLink, delay='20ms')
        self.addLink(s68, s73, cls=TCLink, delay='20ms')
        self.addLink(s70, s78, cls=TCLink, delay='11ms')
        self.addLink(s77, s94, cls=TCLink, delay='3ms')
        self.addLink(s78, h99, cls=TCLink, delay='5ms')
        self.addLink(s83, s87, cls=TCLink, delay='18ms')
        self.addLink(s85, s95, cls=TCLink, delay='14ms')
        self.addLink(s86, s89, cls=TCLink, delay='15ms')
        self.addLink(s87, s91, cls=TCLink, delay='18ms')
        self.addLink(s89, s93, cls=TCLink, delay='15ms')
        self.addLink(s94, s97, cls=TCLink, delay='3ms')

topos = {
        'mytopo': (lambda: Network())
}
